# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 637e0c2ce4fcee3ebe64c28e855b989d5a938a6792d9a95ebc64aa91a6b5ebc466bda6798d1f48824de6c63aa9defe93653d9b19ffdc6e59b5edcf09806337ec

test:
  secret_key_base: bff0b74e75ccffcca6796577f71f0576a7faee1bb53bcb13978e7a0bd550a2db66bf3a4a7251fdf81b2e66c912c99c3c0fd807eb3b4333affa388f0d2e780024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
